// Generated by github.com/davyxu/cellnet/objprotogen
// DO NOT EDIT!
package chatproto

import (
	"github.com/davyxu/cellnet"
	"reflect"
	"fmt"
)

func (self *ChatREQ) String() string   { return fmt.Sprintf("%+v", *self) }
func (self *ChatACK) String() string   { return fmt.Sprintf("%+v", *self) }
func (self *RenameACK) String() string { return fmt.Sprintf("%+v", *self) }

func init() {

	cellnet.RegisterMessageMeta("binary", "chatproto.ChatREQ", reflect.TypeOf((*ChatREQ)(nil)).Elem(), 1663497553)
	cellnet.RegisterMessageMeta("binary", "chatproto.ChatACK", reflect.TypeOf((*ChatACK)(nil)).Elem(), 142346547)
	cellnet.RegisterMessageMeta("binary", "chatproto.RenameACK", reflect.TypeOf((*RenameACK)(nil)).Elem(), 1608756819)
}
